language: python
python: 3.6
install: pip3 install .
script: python3 setup.py test
deploy:
  skip_cleanup: true
  provider: pypi
  user: wcrichto
  on:
    tags: true
    distributions: sdist bdist_wheel
