language: node_js
node_js: 10
before_install:
- pyenv install --skip-existing 3.7 && pyenv global 3.7
- pip3 install --upgrade setuptools
- git clone https://github.com/berkerpeksag/astor/
- pushd astor && pip3 install . && popd
install:
- pushd inliner_jupyter && npm install && npm run prepublishOnly && popd
script: travis_wait python3.7 setup.py test
deploy:
- skip_cleanup: true
  provider: pypi
  user: wcrichto
  on:
    tags: true
    distributions: bdist_wheel
  password:
    secure: GQJuNBrv6jlrr+T30iaOpEgMLSmirzSU6gL09U8RL/Jj4fBqUi16S8sdu2fbpONynb0xNE/9RwNCyH9HiOHoI870XFZh5DutPv86LcekwTq9L679KxByDF9LUWlXUUiA56w5h62dgZ94zlwFIlbhrD0W7udKFe1NhQ7VSm48Ek4A9eQ7lc13znIo1AndjIfHW0+jpjzaKr5KTQhylp03I0vYsP5Q/2zbL7yx8h2b3IJInOPYpWHVjufOp1s/jPuv9x+dq/e/zDjdv7MUSEaEnX+EOrcL7CBryJBpU5hXhXzz3wOqGxodyRvqRmnNpwvF+DzVb/M3+kO6zoOZ50rUloDkLzQ1JfqLMMAcsmd2d2CnrG48EejAYcOrl2oq0A7835s4komsBrSmG8UCVJdnbrv3s1WmP6JEXpGJQhaEJZSHnAIFkJj9idKTiJvLdZ2s3rGMeXtKvqfH6gqVHM6wrecKQbFCqVeGeoBH5gVnd1BJclbqdsHtvH7NLlTmwkFwj2CIt+NHnJeNCUUBSKj/Wkx5xxaxbM7pnV+6UVzQGPd8YU81nq2KgU/rPRZGTcgaEHqd7+YyfGTQJCArsb2iuhwc4Uc6VpRvyv5gSfUtECK7/tFspl9VQQDX0x1K1n9Qs4MMHbktsBma6A9mr7xIgxnH9+/LJxO0prl+Vk97NGo=
- skip_cleanup: true
  provider: npm
  email: wcrichto@cs.stanford.edu
  api_key:
    secure: qpbKeao//U2AuJA2uWVNPlVD1XYgk8/23PFrCRHz3ck+NcFOxbDWk2I6YSKwOsMoOmuyxvvYbeX+eehSmm+9gRduVkC48WYtFdZ/AZRNWgUBjsBlD0FdWvGBenssaXsuM2ztywMOlWbe+I3yjniZpleCmeno9LV4bYkv3/xzL8o6pxkUlMlquSpz0usQK34q38TOW5UatsM194bI5eRWuvSllz+hi70o4uY7JeboH5O72Ysn6Dc1PhM8ZwR5uQ7O18Fi6HVKV4hopoJ3QidtOyTsS6zXFM18jbwSB0Mnke5jyURDhffQYuIr/8LqW+UUOcij2bAo+eWUJpMExqA0GYpo5NgbRYPNimrlOutFcKaPF4Y4t55z17T3+wFBslCLhnwo+sxjcKI8OOS6lQdUCxW0kLcMdO+P1y2B+PVT8DL8Fy14L7gKxLepvA/QSyFD4bkoUipJ6RroJxpI7712op9dv/WxfcvuV2IgxKvieaRUOEIfo8DHxG0qmbxG8HYSyd4hU9OtnPDmmoKNGZrqMiPbFvk48KdCcAmcpUqfNZ59kx+pXzNdoCTydhyDhtetKRQsrVn8JRfIDtrfCqy4vjgmL+B+Be6xeZBydzJ1or/WIgD4Vuu0Wn5tYYGxsTOEKXbHdeNfDrHeVFlo/Zu4BIzakUUxfuxnWVg93E6kSCg=
  on:
    tags: true
