language: python
python: 3.6
before_install:
  - git clone https://github.com/berkerpeksag/astor/
  - cd astor && pip3 install .
install: pip3 install .
script: python3 setup.py test
deploy:
  skip_cleanup: true
  provider: pypi
  user: wcrichto
  on:
    tags: true
    distributions: sdist bdist_wheel
  password:
    secure: GQJuNBrv6jlrr+T30iaOpEgMLSmirzSU6gL09U8RL/Jj4fBqUi16S8sdu2fbpONynb0xNE/9RwNCyH9HiOHoI870XFZh5DutPv86LcekwTq9L679KxByDF9LUWlXUUiA56w5h62dgZ94zlwFIlbhrD0W7udKFe1NhQ7VSm48Ek4A9eQ7lc13znIo1AndjIfHW0+jpjzaKr5KTQhylp03I0vYsP5Q/2zbL7yx8h2b3IJInOPYpWHVjufOp1s/jPuv9x+dq/e/zDjdv7MUSEaEnX+EOrcL7CBryJBpU5hXhXzz3wOqGxodyRvqRmnNpwvF+DzVb/M3+kO6zoOZ50rUloDkLzQ1JfqLMMAcsmd2d2CnrG48EejAYcOrl2oq0A7835s4komsBrSmG8UCVJdnbrv3s1WmP6JEXpGJQhaEJZSHnAIFkJj9idKTiJvLdZ2s3rGMeXtKvqfH6gqVHM6wrecKQbFCqVeGeoBH5gVnd1BJclbqdsHtvH7NLlTmwkFwj2CIt+NHnJeNCUUBSKj/Wkx5xxaxbM7pnV+6UVzQGPd8YU81nq2KgU/rPRZGTcgaEHqd7+YyfGTQJCArsb2iuhwc4Uc6VpRvyv5gSfUtECK7/tFspl9VQQDX0x1K1n9Qs4MMHbktsBma6A9mr7xIgxnH9+/LJxO0prl+Vk97NGo=
